#!/bin/sh

set -E
trap 'echo Failed on line: $LINENO' ERR

# super
mod="Mod4"

riverctl map normal $mod+Shift Q exit

# manage tiling views
riverctl map normal $mod+Shift C close
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous
# send view to top of stack
riverctl map normal $mod Return zoom

riverctl map normal $mod F toggle-fullscreen

# output controls (useless for now)
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# rivercarro
riverctl map normal $mod H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivercarro "main-ratio +0.05"
riverctl map normal $mod+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivercarro "main-count -1"
riverctl map normal $mod C send-layout-cmd rivercarro "main-location left"
riverctl map normal $mod X send-layout-cmd rivercarro "main-location monocle"

# floating
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map-pointer normal $mod BTN_BACK toggle-float

riverctl map normal $mod+Shift T toggle-float

# tags
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    # focused
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Control $i toggle-focused-tags $tags
    # view's tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# apps
riverctl map normal $mod T spawn "foot"
riverctl map normal $mod+Alt B spawn "swaylock"
# TODO real config file
riverctl map normal $mod S spawn "fuzzel -f 'sans-serif' -T 'foot -e' -b '1d2021e0' -t 'ebdbb2ff' -m 'fb3934ff' -s '3c3836f0' -S 'ebdbb2ff' -B 3 -C 'b8bb26ff'"

# both locked and unl
for mode in normal locked; do
    riverctl map $mode None Print spawn "swappyshot"
    # screenshot without slurp
    riverctl map $mode Shift Print spawn "grim - | swappy -f -"

    # TODO pipewire
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # altdesktop/playerctl
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # haikarainen/light
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

riverctl background-color 0x1d2021
riverctl border-color-focused 0xfabd2f
riverctl border-color-unfocused 0x1d2021
riverctl border-color-urgent 0xfb4934
riverctl border-width 3

# Set repeat rate
riverctl set-repeat 25 660

riverctl rule-add -title "Picture-in-Picture" float
riverctl rule-add ssd

riverctl focus-follows-cursor always

SG=pointer-1241-41217-HID_04d9:a101
LT=pointer-1133-4136-Logitech_M570
LM=pointer-1133-16468-Logitech_Wireless_Mouse
TP=pointer-1267-32-Elan_Touchpad
EX=pointer-1390-252-ELECOM_ELECOM_TrackBall_Mouse
AD=pointer-20547-23623-Ploopy_Corporation_Ploopy_Adept_Trackball_Mouse

# patch gone, use flat now
# own river patch!
# riverctl input $SG accel-profile custom
# riverctl input $SG custom-accel 130 0.3 1.5 1.5
# riverctl input $SG scroll-button BTN_MIDDLE
# riverctl input $SG scroll-method button

riverctl input $LT accel-profile flat
riverctl input $LT pointer-accel 0
# riverctl input $LT accel-profile custom
# riverctl input $LT custom-accel 1 2 2
# riverctl input $LT scroll-button BTN_MIDDLE
# riverctl input $LT scroll-method button
#
riverctl input $EX accel-profile flat
riverctl input $EX pointer-accel 0

riverctl input $AD accel-profile flat
riverctl input $AD pointer-accel 0

riverctl input $LM accel-profile flat
riverctl input $LM pointer-accel 1

riverctl input $TP tap enabled
riverctl input $TP accel-profile adaptive
riverctl input $TP pointer-accel 0

export XDG_CURRENT_DESKTOP=river
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
wmname LG3D # java
import-gsettings

riverctl default-layout rivercarro
gammastep -PO 4800 &
waybar &
mako &
swaybg -i ~/bgs/alpenglow.jpg -m fill &
lxpolkit &
rivercarro -main-ratio 0.5 -inner-gaps 16 -outer-gaps 16 &
