#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Use the "logo" key as the primary modifier
mod="Mod4"

# Mod+T to start an instance of foot
riverctl map normal $mod T spawn "foot"

# Mod+Shift+C to close the focused view
riverctl map normal $mod+Shift C close

# Mod+Shift+Q to exit river
riverctl map normal $mod+Shift Q exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom


# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivercarro "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivercarro "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move up 100
riverctl map normal $mod+Mod1 K move down 100
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control J snap left
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap down
riverctl map normal $mod+Mod1+Control Semicolon snap right

# Mod+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# make a floating mode
riverctl declare-mode floating-manage
riverctl map normal $mod A enter-mode floating-manage
riverctl map floating-manage $mod A enter-mode normal
riverctl map-pointer normal None BTN_TASK enter-mode floating-manage
riverctl map-pointer floating-manage None BTN_TASK enter-mode normal
riverctl map-pointer floating-manage None BTN_LEFT move-view
riverctl map-pointer floating-manage None BTN_RIGHT resize-view
riverctl map-pointer floating-manage None BTN_BACK toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+Shift+T to toggle float
riverctl map normal $mod+Shift T toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

riverctl map normal $mod C send-layout-cmd rivercarro "main-location left"
riverctl map normal $mod X send-layout-cmd rivercarro "main-location monocle"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

riverctl map normal $mod+Alt B spawn "swaylock"

# launcher
riverctl map normal $mod S spawn "fuzzel -f 'sans-serif' -T 'foot -e' -b '282828e0' -t 'ebdbb2ff' -m 'fb3934ff' -s '1d2021f0' -S 'ebdbb2ff'"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do

    riverctl map $mode None Print spawn "swappyshot"
    # screenshot without slurp
    riverctl map $mode Shift Print spawn "grim - | swappy -f -"

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set background and border color
riverctl background-color 0x1d2021
riverctl border-color-focused 0xb8bb26
riverctl border-color-unfocused 0x1d2021
riverctl border-width 3

# Set repeat rate
riverctl set-repeat 25 660

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "Picture-in-Picture"

riverctl focus-follows-cursor normal

MYMOUSE=pointer-1390-296-ELECOM_TrackBall_Mouse_EX-G_Pro_TrackBall_Mouse
riverctl input $MYMOUSE accel-profile flat
riverctl input $MYMOUSE pointer-accel -0.4

# Startup commands
export XDG_CURRENT_DESKTOP=river
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river # gtk stuff
wmname LG3D # java
import-gsettings
gammastep -PO 4800 -g1.15 &
waybar &
mako &
swaybg -i ~/bgs/alpenglow.jpg &
lxpolkit &

riverctl default-layout rivercarro
exec rivercarro -main-ratio 0.5
