#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivercarro(1) man pages for complete
# documentation.

# Use the "logo" key as the primary modifier
mod="Mod4"

# Mod+T to start an instance of kitty
riverctl map normal $mod T spawn "kitty"

# Mod+Shift+C to close the focused view
riverctl map normal $mod+Shift C close

# Mod+Shift+Q to exit river
riverctl map normal $mod+Shift Q exit

# Mod+L and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod L focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+L and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift L swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom

# Mod+J and Mod+Semicolon to decrease/increase the main ratio of rivercarro(1)
riverctl map normal $mod J send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal $mod Semicolon send-layout-cmd rivercarro "main-ratio +0.05"

# Mod+Shift+J and Mod+Shift+Semicolon to increment/decrement the main count of rivercarro(1)
riverctl map normal $mod+Shift J send-layout-cmd rivercarro "main-count +1"
riverctl map normal $mod+Shift Semicolon send-layout-cmd rivercarro "main-count -1"

# Mod+Alt+{J,K,L,Semicolon} to move views
riverctl map normal $mod+Mod1 J move left 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move down 100
riverctl map normal $mod+Mod1 Semicolon move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control J snap left
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap down
riverctl map normal $mod+Mod1+Control Semicolon snap right

# Mod+Alt+Shif+{J,K,L,Semicolon} to resize views
riverctl map normal $mod+Mod1+Shift J resize horizontal -100
riverctl map normal $mod+Mod1+Shift K resize vertical 100
riverctl map normal $mod+Mod1+Shift L resize vertical -100
riverctl map normal $mod+Mod1+Shift Semicolon resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+Shift+T to toggle float
riverctl map normal $mod+Shift T toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod V       send-layout-cmd rivercarro "main-location top"
riverctl map normal $mod+Shift V send-layout-cmd rivercarro "main-location bottom"
riverctl map normal $mod B       send-layout-cmd rivercarro "main-location left"
riverctl map normal $mod+Shift B send-layout-cmd rivercarro "main-location right"

riverctl map normal $mod X       send-layout-cmd rivercarro "main-location monocle"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# lock
riverctl map normal $mod+Control L spawn "waylock"

# launcher
riverctl map normal $mod S spawn "fuzzel -f \"sans-serif\" -T \"kitty -e\" -b \"282828e0\" -t \"ebdbb2ff\" -m \"fb3934ff\" -s \"1d2021f0\" -S \"ebdbb2ff\""

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do

    riverctl map $mode None Print spawn "grim -g \"\$(slurp)\" - | swappy -f -"

    # Eject the optical drive
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set background and border color
riverctl background-color 0x1d2021
riverctl border-color-focused 0xb8bb26
riverctl border-color-unfocused 0x1d2021

# Set repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "Picture-in-Picture"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

riverctl focus-follows-cursor normal

# Set and exec into the default layout generator, rivercarro.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro

riverctl input 1390:252:ELECOM_ELECOM_TrackBall_Mouse accel-profile flat

# Startup commands
import-gsettings
pipewire &
pipewire-pulse &
wlsunset -t 4800 -T 4801 &
waybar &

exec rivercarro

